apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::052587224384:role/banksystem-github-action-role
      username: banksystem-github-action-role
      groups:
        - system:masters