apiVersion: v1
kind: Service
metadata:
  name: bank-system-api-service
spec:
  selector:
    app: bank-system-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: http-server
      name: http-service
    - protocol: TCP
      port: 90
      targetPort: grpc-server
      name: grpc-service
    
  type: ClusterIP